name: poupehoje
description: Uma app para gerir e poupar dinheiro no dia a dia — PoupeHoje.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0
  flutter_animate: ^4.5.0

  flutter_localizations:
    sdk: flutter
  # Firebase Core & Auth
  firebase_core: ^3.15.2
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.1.0


  google_sign_in: ^6.2.1
  # Gestão de estado
  provider: ^6.1.2

  # Armazenamento local
  shared_preferences: ^2.3.3

  # Internacionalização e formatação
  intl: 0.20.2

  # UI e ícones
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8

  # Gráficos
  fl_chart: ^0.68.0
  # syncfusion_flutter_charts: ^26.2.8

  # Animações e navegação moderna
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android_12:
    color: "#FFFFFF"
    image: assets/icon.png

