// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLukWSNKFCXq8-nkhKx3KQPENVYGMQSVM',
    appId: '1:159849474533:web:d0ff4f0707fa8d3a55e70c',
    messagingSenderId: '159849474533',
    projectId: 'poupehoje-8b8a4',
    authDomain: 'poupehoje-8b8a4.firebaseapp.com',
    storageBucket: 'poupehoje-8b8a4.firebasestorage.app',
    measurementId: 'G-K3DPKD4TB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnYI6hiCgPe1QhEYsleg9ue6w86VlgUk',
    appId: '1:159849474533:android:8826f5c02320916c55e70c',
    messagingSenderId: '159849474533',
    projectId: 'poupehoje-8b8a4',
    storageBucket: 'poupehoje-8b8a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyzNYeRZLTBw6HSb6oAmv8NmgplAU5xc',
    appId: '1:159849474533:ios:8e5c85b639148b1555e70c',
    messagingSenderId: '159849474533',
    projectId: 'poupehoje-8b8a4',
    storageBucket: 'poupehoje-8b8a4.firebasestorage.app',
    iosBundleId: 'com.example.poupehoje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzyzNYeRZLTBw6HSb6oAmv8NmgplAU5xc',
    appId: '1:159849474533:ios:8e5c85b639148b1555e70c',
    messagingSenderId: '159849474533',
    projectId: 'poupehoje-8b8a4',
    storageBucket: 'poupehoje-8b8a4.firebasestorage.app',
    iosBundleId: 'com.example.poupehoje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLukWSNKFCXq8-nkhKx3KQPENVYGMQSVM',
    appId: '1:159849474533:web:26b3f70cb660162755e70c',
    messagingSenderId: '159849474533',
    projectId: 'poupehoje-8b8a4',
    authDomain: 'poupehoje-8b8a4.firebaseapp.com',
    storageBucket: 'poupehoje-8b8a4.firebasestorage.app',
    measurementId: 'G-8R8MJR4H59',
  );
}
